#!/usr/bin/env python3
"""Runner for autonomous autoconstructor agents.

This script is intended to be executed by CI (GitHub Actions) or manually.
It will call the example code agent to propose and (by default) submit a PR.
"""
import argparse
import logging
from autoconstructor.agents.code_agent import propose_and_submit

logging.basicConfig(level=logging.INFO)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--repo", default="srodolfobarbosa-afk/Nexo", help="full repo name owner/repo")
    p.add_argument("--file", default="autoconstructor/autogenerated.txt", help="file path to write")
    p.add_argument("--intent", default="Autonomous update by agent", help="intent description")
    p.add_argument("--auto-apply", action="store_true", help="if set, attempt to apply changes (requires token)")
    args = p.parse_args()

    logging.info("Running autoconstructor runner")
    try:
        # auto_apply True by default for autonomy; but allow CLI override
        auto_apply = True if args.auto_apply or True else False
        res = propose_and_submit(args.repo, args.file, args.intent, auto_apply=auto_apply)
        logging.info("Result: %s", res)
    except Exception as e:
        logging.exception("Runner failed: %s", e)
        raise


if __name__ == "__main__":
    main()
